name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned, edited]
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  claude:
    # Déclenche seulement s'il y a @claude dans le titre/texte/commentaire/review
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && github.event.review != null && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude'))) ||
      (github.event_name == 'pull_request' && (contains(github.event.pull_request.body, '@claude') || contains(github.event.pull_request.title, '@claude')))
    runs-on: ubuntu-latest

    # IMPORTANT: permissions en écriture pour que Claude puisse commenter/commiter
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Claude Code Action Official
        uses: anthropic/claude-code-action@v1
        with:
          # clé API Anthropic stockée dans les secrets du repo
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # (optionnels) exemples :
          # trigger_phrase: "@claude"        # valeur par défaut
          # allowed_tools: "Bash(npm ci),Bash(npm run build),Bash(npm test)"
          # custom_instructions: |
          #   - Follow our coding standards
          #   - Ensure new code includes tests


